# Generated by Django 6.0.4 on 2026-04-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('CAO', 'Cão'), ('GATO', 'Gato'), ('OUTRO', 'Outro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('MACHO', 'Macho'), ('FEMEA', 'Fêmea')], max_length=10),
        ),
    ]
