# Generated by Django 6.0.4 on 2026-04-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_animal_especie_alter_animal_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='especie_outro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
