# Generated by Django 6.0.4 on 2026-04-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_animal_especie_outro'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('FALECIDO', 'Falecido')], default='ATIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='ObitoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_obito', models.DateField(auto_now_add=True)),
                ('origem', models.CharField(choices=[('ATENDIMENTO', 'Atendimento'), ('CASTRACAO', 'Castração'), ('VISITA', 'Visita'), ('OUTRO', 'Outro')], max_length=20)),
                ('tipo', models.CharField(choices=[('OBITO', 'Óbito natural'), ('EUTANASIA', 'Eutanásia')], max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obitos', to='cadastros.animal')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.tutor')),
            ],
        ),
    ]
