# Generated by Django 6.0.4 on 2026-04-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_animal_status_obitoanimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFalecido',
            fields=[
            ],
            options={
                'verbose_name': 'Animal falecido',
                'verbose_name_plural': 'Animais falecidos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cadastros.animal',),
        ),
    ]
