# Generated by Django 6.0.4 on 2026-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_animalfalecido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='obitoanimal',
            options={'verbose_name': 'Óbito de animal', 'verbose_name_plural': 'Óbitos de animais'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
    ]
