# Generated by Django 6.0.4 on 2026-05-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_animal_options_alter_obitoanimal_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalFalecido',
        ),
    ]
