# Generated by Django 6.0.5 on 2026-05-14 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_delete_animalfalecido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['nome'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='obitoanimal',
            options={'ordering': ['-data_obito'], 'verbose_name': 'Óbito de animal', 'verbose_name_plural': 'Óbitos de animais'},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['nome'], 'verbose_name': 'Tutor', 'verbose_name_plural': 'Tutores'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('CAO', 'Cão'), ('GATO', 'Gato'), ('OUTRO', 'Outro')], max_length=10, verbose_name='Espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie_outro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Outra espécie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade_aproximada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Idade aproximada'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='raca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('MACHO', 'Macho'), ('FEMEA', 'Fêmea')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('FALECIDO', 'Falecido')], default='ATIVO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='cadastros.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='obitoanimal',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obitos', to='cadastros.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='obitoanimal',
            name='data_obito',
            field=models.DateField(auto_now_add=True, verbose_name='Data do óbito'),
        ),
        migrations.AlterField(
            model_name='obitoanimal',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='obitoanimal',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='obitoanimal',
            name='origem',
            field=models.CharField(choices=[('ATENDIMENTO', 'Atendimento'), ('CASTRACAO', 'Castração'), ('VISITA', 'Visita'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='obitoanimal',
            name='tipo',
            field=models.CharField(choices=[('OBITO', 'Óbito natural'), ('EUTANASIA', 'Eutanásia')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='obitoanimal',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='endereco',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
    ]
