# Generated by Django 6.0.8 on 2026-08-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_animal_options_alter_obitoanimal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(blank=True, help_text='Pode deixar em branco se o animal faltou e o nome ainda não é conhecido.', max_length=100, verbose_name='Nome'),
        ),
    ]