# Generated by Django 6.0.4 on 2026-09-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_animal_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
