# Generated by Django 6.0.4 on 2026-04-24 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('queixa_principal', models.TextField()),
                ('historico_clinico', models.TextField(blank=True, null=True)),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamento', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('peso_no_atendimento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em atendimento'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=20)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='cadastros.animal')),
                ('veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
