# Generated by Django 6.0.4 on 2026-04-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='doenca_confirmada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_confirmados', to='atendimentos.doenca'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='doencas',
            field=models.ManyToManyField(blank=True, to='atendimentos.doenca'),
        ),
    ]
