# Generated by Django 6.0.4 on 2026-04-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_doenca_atendimento_doenca_confirmada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='atendimentos/fotos/')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='atendimentos.atendimento')),
            ],
        ),
    ]
