# Generated by Django 6.0.4 on 2026-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_fotoatendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='houve_eutanasia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='houve_obito',
            field=models.BooleanField(default=False),
        ),
    ]
