# Generated by Django 6.0.4 on 2026-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_atendimento_houve_eutanasia_atendimento_houve_obito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
        migrations.AlterModelOptions(
            name='doenca',
            options={'verbose_name': 'Doença', 'verbose_name_plural': 'Doenças'},
        ),
        migrations.AlterModelOptions(
            name='fotoatendimento',
            options={'verbose_name': 'Foto do atendimento', 'verbose_name_plural': 'Fotos dos atendimentos'},
        ),
    ]
