# Generated by Django 6.0.4 on 2026-05-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0005_alter_atendimento_options_alter_doenca_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='houve_eutanasia',
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='houve_obito',
        ),
    ]
