# Generated by Django 6.0.5 on 2026-05-14 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0006_remove_atendimento_houve_eutanasia_and_more'),
        ('cadastros', '0008_alter_animal_options_alter_obitoanimal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='cadastros.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do atendimento'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='doenca_confirmada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_confirmados', to='atendimentos.doenca', verbose_name='Doença confirmada'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='doencas',
            field=models.ManyToManyField(blank=True, to='atendimentos.doenca', verbose_name='Doenças'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='historico_clinico',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico clínico'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='peso_no_atendimento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso no atendimento (kg)'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='queixa_principal',
            field=models.TextField(verbose_name='Queixa principal'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='sintomas',
            field=models.TextField(blank=True, null=True, verbose_name='Sintomas'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ATENDIMENTO', 'Em atendimento'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='tratamento',
            field=models.TextField(blank=True, null=True, verbose_name='Tratamento'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='veterinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to=settings.AUTH_USER_MODEL, verbose_name='Veterinária'),
        ),
        migrations.AlterField(
            model_name='doenca',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='fotoatendimento',
            name='atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='atendimentos.atendimento', verbose_name='Atendimento'),
        ),
        migrations.AlterField(
            model_name='fotoatendimento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='fotoatendimento',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='fotoatendimento',
            name='imagem',
            field=models.ImageField(upload_to='atendimentos/fotos/', verbose_name='Imagem'),
        ),
    ]
