# Generated by Django 6.0.4 on 2026-04-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUTORIZACAO_PROCEDIMENTO', 'Autorização de Procedimento'), ('EUTANASIA', 'Termo de Eutanásia'), ('EXAME', 'Exame'), ('OUTRO', 'Outro')], max_length=40)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='cadastros.animal')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='cadastros.tutor')),
            ],
        ),
    ]
