# Generated by Django 6.0.4 on 2026-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacaoProcedimento',
            fields=[
            ],
            options={
                'verbose_name': 'Autorização de procedimento',
                'verbose_name_plural': 'Autorizações de procedimento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documentos.documento',),
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documentos.documento',),
        ),
        migrations.CreateModel(
            name='OutroDocumento',
            fields=[
            ],
            options={
                'verbose_name': 'Outro documento',
                'verbose_name_plural': 'Outros documentos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documentos.documento',),
        ),
        migrations.CreateModel(
            name='TermoEutanasia',
            fields=[
            ],
            options={
                'verbose_name': 'Termo de eutanásia',
                'verbose_name_plural': 'Termos de eutanásia',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('documentos.documento',),
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
