# Generated by Django 6.0.5 on 2026-05-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_animal_options_alter_obitoanimal_options_and_more'),
        ('documentos', '0002_autorizacaoprocedimento_exame_outrodocumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cadastros.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to='documentos/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('EUTANASIA', 'Termo de eutanásia'), ('AUTORIZACAO_PROCEDIMENTO', 'Autorização de procedimento'), ('EXAME', 'Exame'), ('OUTRO', 'Outro')], max_length=30, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cadastros.tutor', verbose_name='Tutor'),
        ),
    ]
