# Generated by Django 6.0.4 on 2026-04-30 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimentos', '0003_fotoatendimento'),
        ('cadastros', '0004_animal_status_obitoanimal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('RURAL', 'Zona rural'), ('URBANA', 'Zona urbana')], max_length=20)),
                ('setor', models.CharField(max_length=20)),
                ('quadra', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_animal_nao_cadastrado', models.CharField(blank=True, max_length=100, null=True)),
                ('data_visita', models.DateField()),
                ('situacao', models.CharField(choices=[('NORMAL', 'Visita normal'), ('CASA_FECHADA', 'Casa fechada'), ('RECUSA', 'Recusa'), ('OUTRO', 'Outro')], default='NORMAL', max_length=30)),
                ('houve_eutanasia', models.BooleanField(default=False)),
                ('houve_obito', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='cadastros.animal')),
                ('doencas_positivas', models.ManyToManyField(blank=True, to='atendimentos.doenca')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='cadastros.tutor')),
            ],
        ),
    ]
