# Generated by Django 6.0.4 on 2026-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
    ]
