# Generated by Django 6.0.4 on 2026-05-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_alter_visita_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='houve_eutanasia',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='houve_obito',
        ),
    ]
