# Generated by Django 6.0.5 on 2026-05-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0007_alter_atendimento_animal_and_more'),
        ('cadastros', '0008_alter_animal_options_alter_obitoanimal_options_and_more'),
        ('visitas', '0003_remove_visita_houve_eutanasia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='cadastros.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='area',
            field=models.CharField(choices=[('RURAL', 'Zona rural'), ('URBANA', 'Zona urbana')], max_length=20, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='data_visita',
            field=models.DateField(verbose_name='Data da visita'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='doencas_positivas',
            field=models.ManyToManyField(blank=True, to='atendimentos.doenca', verbose_name='Doenças positivas'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='endereco',
            field=models.TextField(verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='nome_animal_nao_cadastrado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do animal (não cadastrado)'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='nome_responsavel',
            field=models.CharField(max_length=100, verbose_name='Nome do responsável'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='quadra',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Quadra'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='setor',
            field=models.CharField(max_length=20, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='situacao',
            field=models.CharField(choices=[('NORMAL', 'Visita normal'), ('CASA_FECHADA', 'Casa fechada'), ('RECUSA', 'Recusa'), ('OUTRO', 'Outro')], default='NORMAL', max_length=30, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='cadastros.tutor', verbose_name='Tutor'),
        ),
    ]
