# Generated by Django 6.0.4 on 2026-04-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Castracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField()),
                ('periodo', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde')], max_length=10)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('COMPARECEU', 'Compareceu'), ('FALTOU', 'Faltou'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='castracoes', to='cadastros.animal')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='castracoes', to='cadastros.tutor')),
            ],
        ),
    ]
