# Generated by Django 6.0.4 on 2026-04-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='castracao',
            name='houve_eutanasia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='castracao',
            name='houve_obito',
            field=models.BooleanField(default=False),
        ),
    ]
