# Generated by Django 6.0.4 on 2026-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castracoes', '0002_castracao_houve_eutanasia_castracao_houve_obito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castracao',
            options={'verbose_name': 'Castração', 'verbose_name_plural': 'Castrações'},
        ),
    ]
