# Generated by Django 6.0.4 on 2026-05-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castracoes', '0003_alter_castracao_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castracao',
            name='houve_eutanasia',
        ),
        migrations.RemoveField(
            model_name='castracao',
            name='houve_obito',
        ),
    ]
