# Generated by Django 6.0.5 on 2026-05-14 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_animal_options_alter_obitoanimal_options_and_more'),
        ('castracoes', '0004_remove_castracao_houve_eutanasia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castracao',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='castracoes', to='cadastros.animal', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='castracao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='castracao',
            name='data_agendada',
            field=models.DateField(verbose_name='Data agendada'),
        ),
        migrations.AlterField(
            model_name='castracao',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='castracao',
            name='periodo',
            field=models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde')], max_length=10, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='castracao',
            name='status',
            field=models.CharField(choices=[('AGENDADA', 'Agendada'), ('COMPARECEU', 'Compareceu'), ('FALTOU', 'Faltou'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='AGENDADA', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='castracao',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='castracoes', to='cadastros.tutor', verbose_name='Tutor'),
        ),
    ]
