# Generated by Django 6.0.4 on 2026-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoletimVacinacaoRaiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gve', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(default='Promissão', max_length=100)),
                ('posto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_posto', models.CharField(choices=[('FIXO', 'Fixo'), ('VOLANTE', 'Volante')], max_length=20)),
                ('tipo_vacinacao', models.CharField(choices=[('ROTINA', 'Rotina'), ('CAMPANHA', 'Campanha'), ('COBERTURA_FOCO', 'Cobertura de foco')], max_length=30)),
                ('data', models.DateField()),
                ('caes', models.PositiveIntegerField(default=0)),
                ('gatos', models.PositiveIntegerField(default=0)),
                ('outros', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('responsavel_preenchimento', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
