# Generated by Django 6.0.4 on 2026-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boletimvacinacaoraiva',
            options={'verbose_name': 'Boletim de vacinação antirrábica', 'verbose_name_plural': 'Boletins de vacinação antirrábica'},
        ),
    ]
