# Generated by Django 6.0.5 on 2026-05-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacinacoes', '0002_alter_boletimvacinacaoraiva_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='caes',
            field=models.PositiveIntegerField(default=0, verbose_name='Cães'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='gatos',
            field=models.PositiveIntegerField(default=0, verbose_name='Gatos'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='gve',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GVE'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='municipio',
            field=models.CharField(default='Promissão', max_length=100, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='outros',
            field=models.PositiveIntegerField(default=0, verbose_name='Outros'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='posto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Posto'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='responsavel_preenchimento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável pelo preenchimento'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='tipo_posto',
            field=models.CharField(choices=[('FIXO', 'Fixo'), ('VOLANTE', 'Volante')], max_length=20, verbose_name='Tipo de posto'),
        ),
        migrations.AlterField(
            model_name='boletimvacinacaoraiva',
            name='tipo_vacinacao',
            field=models.CharField(choices=[('ROTINA', 'Rotina'), ('CAMPANHA', 'Campanha'), ('COBERTURA_FOCO', 'Cobertura de foco')], max_length=30, verbose_name='Tipo de vacinação'),
        ),
    ]
